trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: npm install -g snyk
    displayName: 'Install Snyk CLI'

  - script: snyk config environment SNYK-US-02
    displayName: 'Set Snyk region'

  - script: snyk auth $(SNYK_TOKEN)
    displayName: 'Authenticate Snyk'
    env:
      SNYK_TOKEN: $(SNYK_TOKEN)

  - script: docker build -t juice-shop:latest .
    displayName: 'Build Docker image'

  - script: snyk container test juice-shop:latest --exclude-base-image-vulns --severity-threshold=high --org=dad5720b-dd1d-4159-85f7-d7c58fe11563
    displayName: 'Run Snyk Container Test'
    continueOnError: true

  - script: snyk container monitor juice-shop:latest --org=dad5720b-dd1d-4159-85f7-d7c58fe11563
    displayName: 'Send Container Snapshot to Snyk (Monitor)'
    continueOnError: true